### ISSUE TITLE
Fix sample_data_load_function in simple_workflow/workflow.json

### ISSUE THREAD

**Issue by suguiura** [b12io/orchestra#338]
In `/simple_workflow/workflow.json`, the `sample_data_load_function` object has `module` and `name` keys, but should be replaced by `path`, as in `/journalism_workflow/workflow.json`.

**Comment by joshblum** [comment]
Thanks @suguiura! Bug will be fixed in #339

**Comment by joshblum** [comment]
Closed by #339
