### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by thisisdhaas** [b12io/orchestra#41]
c.f. https://github.com/jasmine/jasmine/blob/master/RELEASE.md

**Comment by thisisdhaas** [comment]
Current known steps:
- Use [Semantic Versioning](http://semver.org/)
- Bump version number in `setup.py`
- Create a new tag (prepending the version string with 'v', as in `v0.1.2`).
- Move the `stable` tag to point to the new tag.
- Push to pypi (sdist)

**Comment by marcua** [comment]
Also: can this be a script?

**Comment by thisisdhaas** [comment]
#53 Implements this as a script, so documentation isn't necessary.
