### ISSUE TITLE
Timer errors in Getting Started app

### ISSUE THREAD

**Issue by chris-hailstorm** [b12io/orchestra#439]
Using the Getting Started guide -- visited http://127.0.0.1:8000/orchestra/app/.

The page opens, followed by two error popups:

    127.0.0.1:8000 says: Could not get timer.

and

    127.0.0.1:8000 says: Could not retrieve time entries

**Comment by marcua** [comment]
@chris-hailstorm Great to report this. I've seen this pop up in situations where Django `User`s who are not fully set up as Orchestra `Worker`s open the Orchestra dashboard. Could you open your browser's developer console and copy/paste any network requests/responses with 4XX / 5XX responses? Usually this would live in the Network tab.

**Comment by davidkrcil** [comment]
I have the some issue and confirm the consequence with user without worker set

**Comment by marcua** [comment]
Thanks for reporting this, and sorry for the confusion! We updated [the documentation](https://orchestra.readthedocs.io/en/latest/getting_started.html) to clarify:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/57725/57859137-59786780-77c0-11e9-9f36-f824a9de5352.png">
