### ISSUE TITLE
Error after New delivery task button pressed

### ISSUE THREAD

**Issue by davidkrcil** [b12io/orchestra#446]
This I get when press New delivery task button

{"error": 500, "message": "CommunicationPreference matching query does not exist.", "traceback": "Traceback (most recent call last):\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/jsonview/decorators.py\", line 74, in _wrapped\n    ret = f(request, *a, **kw)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py\", line 23, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/views.py\", line 127, in new_task_assignment\n    task_assignment = get_new_task_assignment(worker, task_status)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/utils/task_lifecycle.py\", line 750, in get_new_task_assignment\n    task = assign_task(worker.id, task.id)\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py\", line 53, in inner\n    return func(*args, **kwds)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/utils/task_lifecycle.py\", line 249, in assign_task\n    notify_status_change(task, previous_status)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/utils/notifications.py\", line 98, in notify_status_change\n    **message_info)\n  File 
\"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/communication/mail.py\", line 22, in send_mail\n    email for email in recipient_list\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/communication/mail.py\", line 23, in <listcomp>\n    if _can_email(communication_type, email)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/orchestra/communication/mail.py\", line 53, in _can_email\n    communication_type=communication_type\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/django/db/models/query.py\", line 380, in get\n    self.model._meta.object_name\norchestra.models.communication.models.DoesNotExist: CommunicationPreference matching query does not exist.\n"}

**Comment by pohyk123** [comment]
You need to fill up any of your workers' communication preferences under the django admin board.
http://127.0.0.1:8000/orchestra/admin/orchestra/communicationpreference/

Perhaps future versions can remove the necessity of this feature before workers are able to receive any tasks.
