### ISSUE TITLE
MultipleObjectsReturned error after Accepting a task from /orchestra/communication/available_staffing_requests/

### ISSUE THREAD

**Issue by davidkrcil** [b12io/orchestra#447]
Does somebody know why I get this error after I click button Accept task from /orchestra/communication/available_staffing_requests/
?

Request Method: | GET
-- | --
http://127.0.0.1:8000/orchestra/communication/accept_staffing_request_inquiry/71/
1.11.10
MultipleObjectsReturned
get() returned more than one Worker -- it returned 2!
/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/lib/python3.6/site-packages/django/db/models/query.py in get, line 384
/Users/davidkrcil/PycharmProjects/orchestraAgain/venv/bin/python

**Comment by HemilModi03** [comment]
@davidkrcil were you able to solve this one ?
