### ISSUE TITLE
Missing template tag "hijack_tags"

### ISSUE THREAD

**Issue by richwandell** [b12io/orchestra#67]
Fresh install throwing an error about a missing template tag.

![screen shot 2015-10-28 at 2 11 51 pm](https://cloud.githubusercontent.com/assets/772607/10798459/25e0db04-7d7e-11e5-9480-a3e91365fc74.png)

**Comment by richwandell** [comment]
was able to fix this by adding 'hijack' to my installed apps. might want to add this to the docs

**Comment by thisisdhaas** [comment]
We added hijack as a feature recently, which made non-backwards-compatible changes to `orchestra_settings.py`. I'm assuming you had already set up orchestra before and had an old version of `orchestra_settings.py`. A fresh install should pull down our latest version, which contains the new apps (https://github.com/unlimitedlabs/orchestra/blob/v0.1.7/example_project/example_project/orchestra_settings.py#L46-L47). I'm closing this, but feel free to re-open if I misunderstood the issue or if the problem persists after updating your installed apps.

Sorry about pulling the rug out from under your feet! APIs and requirements will be changing frequently as we iterate on early versions of Orchestra, but we'd like to make that as painless as possible for developers.
